# Generated by Django 3.2 on 2022-09-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='contact',
            name='ven',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contact',
            name='zip',
            field=models.CharField(default='', max_length=70),
        ),
    ]
